---
kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}-{{ .Values.deployment.envTag }}

data:
  {{- toYaml .Values.deployment.payments.env | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}-{{ .Values.deployment.envTag }}
data:
  {{- toYaml .Values.deployment.nginx.env | nindent 2 }}

{{- if eq .Values.deployment.env "developement" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
data:
  nodes: "1"
  allowEmptyPassword: "yes"
{{- end -}}
